AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LaunchTemplateAmiUpdateApp

  Sample SAM Template for LaunchTemplateAmiUpdateApp 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - DEV
      - PROD

Resources:
  LaunchTemplateAmiUpdateFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LaunchTemplateAmiUpdatePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:Describe*
                  - elasticloadbalancing:Describe*
                  - autoscaling:Describe*
                  - ec2:CreateLaunchTemplateVersion
                  - ec2:Describe*
                Resource: '*'
      RoleName: !Sub LaunchTemplateAmiUpdateFunctionRole_${Environment}


  LaunchTemplateAmiUpdateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LaunchTemplateAmiUpdate/
      Role: !GetAtt LaunchTemplateAmiUpdateFunctionRole.Arn
      FunctionName: !Sub LaunchTemplateAmiUpdateFunction_${Environment}
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            RuleName: !Sub LaunchTemplateAmiUpdateEventBridgeRule_${Environment}
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 AMI State Change
              detail:
                State:
                  - available
            Target:
              Id: !Sub LaunchTemplateAmiUpdateFunction_${Environment}
            InputTransformer:
              InputPathsMap:
                "ami": "$.detail.ImageId"
                "state": "$.detail.State"
              InputTemplate: |
                {
                  "ami" : <ami>,
                  "state" : <state>
                }

  LaunchTemplateAmiUpdateFunctionInvocationPermission:
    Type: AWS::Lambda::Permission
    DependsOn: LaunchTemplateAmiUpdateFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub LaunchTemplateAmiUpdateFunction_${Environment}
      Principal: events.amazonaws.com
      SourceArn: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/LaunchTemplateAmiUpdateEventBridgeRule_${Environment}"

  LaunchTemplateAmiUpdateErrorTopic:
    Type: AWS::SNS::Topic # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      TopicName: !Sub LaunchTemplateAmiUpdateErrorTopic_${Environment}
      Subscription:
        - Endpoint: itadmin@polanerselections.com
          Protocol: email

  LaunchTemplateAmiUpdateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub LaunchTemplateAmiUpdateAlarm_${Environment}
      AlarmDescription: Error alarm for LaunchTemplateAmiUpdateFunction
      AlarmActions:
        - !Ref LaunchTemplateAmiUpdateErrorTopic
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref LaunchTemplateAmiUpdateFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      Period: 60
      EvaluationPeriods: 1

  LaunchTemplateAmiUpdateLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LaunchTemplateAmiUpdateFunction}
      RetentionInDays: 7

Outputs:
  LaunchTemplateAmiUpdateFunction:
    Description: "LaunchTemplateAmiUpdate Lambda Function ARN"
    Value: !GetAtt LaunchTemplateAmiUpdateFunction.Arn
  LaunchTemplateAmiUpdateFunctionRole:
    Description: "Implicit IAM Role created for LaunchTemplateAmiUpdate function"
    Value: !GetAtt LaunchTemplateAmiUpdateFunctionRole.Arn
